### ISSUE TITLE
Command line version

### ISSUE THREAD

**Issue by snayfach** [MoriarityLab/EditR#4]
It would be really nice to run EditR from the command line when dealing with many samples. Do you have any suggestions for doing this? Or suggestions for another tool that works well?

**Comment by MitchellKluesner** [comment]
Hi Stephen,

I would recommend checking out the script below from our follow up project, MultiEditR.

I believe that you can use this function by setting the "motif" argument to your protospacer sequence to then return a list object with a tibble element containing the edit information.

Does this help at all?

https://github.com/MoriarityLab/MultiEditR/blob/master/FigureReproduction/scripts/run_for_ngs.R
